# Generated by Django 5.1 on 2024-09-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usermanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="mikrotik_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="mikrotik_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="session",
            name="mikrotik_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mikrotik_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
