# Generated by Django 5.1 on 2024-09-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usermanager", "0002_payment_mikrotik_id_profile_mikrotik_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"ordering": ["-mikrotik_id"]},
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="mikrotik_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
